spring:
  application:
    name: hereandnow

  profiles:
    active: ${ACTIVE_PROFILE}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB_NO}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_OAUTH_CALLBACK}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Google
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_OAUTH_CALLBACK}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

springdoc:
  server-url: ${SERVER_URL}
  override-with-generic-response: false
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: Here&Now API
        url: /v3/api-docs
      - name: NCP CloudFunctions API
        url: /docs/ncp-api.json

jwt:
  secret: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}

cors:
  allow:
    paths: "/**"
    origins: ${CORS_ALLOWED_ORIGINS}
    methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS" ]
    headers:
      - "*"
    exposed-headers:
      - "Authorization"
    max-age: 3600
    credentials: true

oauth2:
  redirect-uri: ${REDIRECT_URI}

ncp:
  access: ${NCP_STORAGE_ACCESS_KEY}
  secret: ${NCP_STORAGE_SECRET_KEY}
  region: ${NCP_STORAGE_REGION}
  endpoint: "https://kr.object.ncloudstorage.com"
  bucket-name: ${NCP_BUCKET_NAME}